(lang dune 3.16)

(name rtimer)

(generate_opam_files true)

(source
 (github rmyazdi/rtimer))

(authors "Rouzbeh Yazdi")

(maintainers "Rouzbeh Yazdi")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name rtimer)
 (synopsis "A Pomodoro Application")
 (description
  "A self-timing application to help you time yourself and focus.")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
